= BasicAI
:toc:
:icons: font

This is the base class for all AI agents.

It implements the core decision engine (through the 'choose' method) and has a 
(rather simple) set of heuristic decisions for every existing scenario.

All AI agents are expected to extend from this class.

== Decision Engine

=== BasicAI.choose(String type, State state, Array choices): any|null

The core decision engine relies on the BasicAI.choose() method. It takes 3 arguments:

* type: The type of choice being asked of the agent
* state: The State object representing the game state
* choices: An array of available options to choose from

Type will be one of the following, currently implemented, choice types:

* CHOICE_DISCARD
* CHOICE_GAIN
* CHOICE_MULTIPLY
* CHOICE_PLAY
* CHOICE_TOPDECK
* CHOICE_TRASH

The choices array may contain different types of elements depending on the
type of choice being asked of the agent. In all the cases, the null choice
represents the "nothing" choice.

For example, considering a hand of Estate, Estate, Copper, Copper, Copper and
asked for an optional trash from hand, the choice() arguments might look
something like this:

* type: CHOICE_TRASH
* state: instance of the state object
* choices: [Estate, Copper, null]

Where null, means "trash nothing".

The core implementation of this decision is based on 2 heuristic functions per
decision type:

* Priority list function (optional)
* Choice value function

If the AI implements a priorityList function, it is consulted in order and the
first entry that matches one of the available choices for the decision is used
as the final choice.

The priority list may contain the `null` value. When evaluating if the
algorithm reaches `null` without having matched any previous choice, then
`null` is used as a final choice if it is an available choice. Every entry
after `null` is usually a non-desired choice prioritized for the case when the
agent is forced to take a specific action, like trashing after playing a
Remodel.

If there is no match, or no priority function, the algorithm uses the
corresponding value function for the decision type. Each available choice is
then assigned a value and the one with the highest value is used.

`null` is considered as a 0 value choice so any non-desired choice should
evaluate to a negative value.

NOTE: There is currently no defined scale for the possible value of a choice.
Look at the definition of each particular value function to see current default
implementations. This will chang in a future version.

=== getChoiceValue(String type, State state, Any choice, Player my):number

Assigns a numerical value to a single choice.

_Usage example_

----
function wantsToPlayBandit (state, my) {
    const gainGoldValue = this.getChoiceValue(CHOICE_GAIN, state, cards.Gold, my);
    return gainGoldValue > 0;
}
----

=== BasicAI.getPriorityFunction(String type): Function|null

Retrieve priority function for a given type if it exists in the AI instance,
`null` otherwise.

_Usage example_

----
const discardPriorityFn = this.getPriorityFunction(CHOICE_DISCARD);
const priorityList = discardPriorityFn(state, my);
----

=== BasicAI.getValueFunction(String type): Function|null

Retrieve value function for a given type if it exists in the AI instance,
`null` otherwise.

_Usage example_

----
const discardValueFn = this.getValueFunction(CHOICE_DISCARD);
let choiceValue = discardValueFn(state, choice, my);
----

=== BasicAI.choiceToValue(String type, State state, Card|String card, Player my): Number

Sometimes we need to compare choices in a strictly numeric way. This takes a
particular choice for a particular choice type, and gets its numeric value.

If the value comes from a priority list, it will be 100 * (distance from end of
list).

So, for example, the default choiceToValue of discarding a Colony is 999, while
the choiceToValue of discarding an extra terminal is 1.

NOTE: Current implementation is very lacking and not able to discern context of
the choice. Will be revisited when I do some normalization work on all the
choice evaluations.

_Usage example_

----
const gainValue = this.choiceToValue(CHOICE_GAIN, state, cards.Province, my);
const trashValue = this.choiceToValue(CHOICE_GAIN, state, cards.Gol, my);
const replaceValue = gainValue - trashValue;
----

== Default Strategy

=== BasicAI.gainPriority(State state, Player my): (String|Card)[]

This is the fallback strategy implementation which is a very simple form of
Big Money.

=== BasicAI.gainValue(State state, Card card, Player my): Number

Assign a value when decision forces to gain a card not in priority list.
All values returned are negative to prefer not gaining a card when available.
Defaults to gaining the most expensive cards, with a bias in favor of actions
and treasures.

=== BasicAI.discardPriority(State state, Player my): (String|Card)[]

The default `discardPriority` is tuned for Big Money where the decisions are
obvious. Many strategies would probably prefer a different priority list,
especially one that knows about action cards.

=== BasicAI.discardValue(State state, Card card, Player my): Number

Evaluates whether it has excess actions and prioritizes actions if so.
Otherwise, discards the cheapest cards. Victory cards would already been
discarded by discardPriority unless customized.

=== BasicAi.trashPriority(State state, Card card, Player my): (String|Card)[]

Pretty obvious trash choices: Curses, Estates, Coppers and also Potions in
late game.

=== BasicAi.trashValue(State state, Card card, Player my): Number

If choice was not in trashPriority assumes trash is undesireable and assigns
all negative values.
By default, we want to trash the card with the lowest (cost + VP).

== Helper Methods

These helper functions allow easy access to the player state or metrics of the
current state.

=== BasicAI.myPlayer(State state): Player

Fetches the player state associated with this instance of the AI.

IMPORTANT: This implies that a single instance of an AI should not be used for
more than one player, otherwise this method
risks returning the incorrect player state.

_Usage example_

----
const my = this.myPlayer(state);
console.log(`I have ${my.getDeck().length} cards in total.`);
----

== Informational Methods

Returns whether the agent is greening. Any positive value is affirmative.

=== BasicAI.goingGreen(State state, Player my): int

_Usage example_

----
function gainPriority(state, my) {
  const priority = [];

  if (this.goingGreen(state, my) > 3) {
    priority.push(cards.Province);
    priority.push(cards.Duchy);
    priority.push(cards.Estate);
  }
}

----
